"""Storage abstractions for runtime state."""

from __future__ import annotations

from typing import Protocol

from awr.domain import Status, WorkItem
from awr.events import Event


class RuntimeStore(Protocol):
    def save_work_item(self, item: WorkItem) -> None: ...
    def get_work_item(self, work_item_id: str) -> WorkItem: ...
    def list_work_items(self) -> list[WorkItem]: ...
    def update_status(self, work_item_id: str, status: Status) -> WorkItem: ...
    def append_event(self, event: Event) -> None: ...
    def list_events(self) -> list[Event]: ...
    def close(self) -> None: ...
